### ISSUE TITLE
can't report

### ISSUE THREAD

**Issue by xensor** [humhub/reportcontent#15]
none of my members can report posts or anything posted on the website. how can i get that to work?

**Comment by simon-roderus** [comment]
Same problem here

**Comment by 001101** [comment]
i can report, but the report is not reported

**Comment by paurosello** [comment]
same problem here

**Comment by 001101** [comment]
it was fixed

**Comment by simon-roderus** [comment]
@001101 Sounds good! Do I have to install a humhub or plugin update?

**Comment by 001101** [comment]
Just update the module, it works for me now for over a month.

**Comment by simon-roderus** [comment]
The latest version in the marketplace is version 0.2.3 and was published on 2015/02. Did you update it directly from github?

Dear plugin-authors: It would be great if you could publish a new version to the marketplace :).

**Comment by Buliwyfa** [comment]
So it u update it form githubs works?

**Comment by andrerudi95** [comment]
Now works perfectly for me

**Comment by simon-roderus** [comment]
Not yet, I wanted to wait until an update is available via the marketplace.
