### ISSUE TITLE
Report Content

### ISSUE THREAD

**Issue by Falko69** [humhub/reportcontent#27]
I installed the Version from humhub. But nothing Shows up.

**Comment by yghost** [comment]
Exactly the same here, installed module but no "report" button anywhere.
Report Content  v 0.2.5
HumHub v 1.3.8

**Comment by buddh4** [comment]
Test the module with a non admin user (simple space member). Note you can't report content of  admins.

**Comment by yghost** [comment]
I've already tested it and it don't work, there is no "report" button with a non admin user on other non admin posts.

**Comment by yghost** [comment]
No sorry, my bad. The first test was done on a "demo" post and it couldn't be reported. But when creating a new user and cross testing again it worked.
Sorry.

**Comment by buddh4** [comment]
No problem its not obvious that this is not working for administrators etc. Should be added to the module readme
