### ISSUE TITLE
Unable to report comments

### ISSUE THREAD

**Issue by lwq057** [humhub/reportcontent#43]
When users publish advertising content or malicious remarks, they cannot be reported in the comments

**Comment by suhmaruh** [comment]
Having the same issue - it seems this module is broken. I wish I knew which update broke it so I could be of more help with diagnosis.

**Comment by timaschew** [comment]
Same for me.  
I'm using HumHub 1.9.2

@luke- any ideas?

**Comment by ArchBlood** [comment]
I believe this updated module should help slightly with this concern (See **alternative** options below), but I would also like to mention that if a post is reported then the admin or whoever has permission can just go through the comments while also determining if the post/comments should be deleted.

### Alternatives
- Add a richtext option for adding more information in a report
- Use https://github.com/Kodmit/HumHub-Advanced-report

Using the Advanced Report module I would like to note that there are issues even with this module, see: https://github.com/Kodmit/HumHub-Advanced-report/issues/1
