### ISSUE TITLE
Links in notifications

### ISSUE THREAD

**Issue by Semir1212** [humhub/reportcontent#60]
When clicking on the report notification (mail or web) a user is forwarded to the dashboard instead of the reported content view.

Ideally is should work something like this:

- User is in default admin group --> always forward to reported content view in admin panel
- User is not in default admin group, but space admin --> forward to reported content view in respective space

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/reportcontent/pull/64.
