### ISSUE TITLE
Indicator for reported content

### ISSUE THREAD

**Issue by Semir1212** [humhub/reportcontent#61]
Currently there are no indicators that there are pending report. Ideally we would add one to the admin panel and to the space settings. Either a simple label or the number of open reports, as already available for other function of the software. 

![image](https://user-images.githubusercontent.com/38326726/227167913-691f22eb-5607-4283-ac02-bd21d2d8f14c.png)

![image](https://user-images.githubusercontent.com/38326726/227168169-1f80d4ea-9fb1-466b-b515-f681a3f5284e.png)

**Comment by luke-** [comment]
@yurabakhtin Can you please check if our menu classes have such an indicator feature?
If not, it might be good to provide a uniform solution here. Because this might also make sense in other places.

**Comment by yurabakhtin** [comment]
@luke- For "Modules" menu item I see this:

![modules](https://user-images.githubusercontent.com/6995524/227225395-85d58102-7c30-4e31-8c49-66ca9a55fb41.png)

but it is not a feature, it is just an appending to the item title https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/widgets/AdminMenu.php#L96:

- `Yii::t('AdminModule.base', 'Modules') . $this->getMarketplaceUpdatesBadge()`
- `getMarketplaceUpdatesBadge()` => `<span class="label label-danger"> $count </span>`

For uniform solution we could implement new option for the `MenuLink` like `'badge' => $count`.
If need we can provide to customize the default style from `danger` to others like `warning`, `info`.
Please confirm to implement the new option `badge` and probably an additional `badgeType` (with values `error`, `warning`, `info`, `success`).

**Comment by luke-** [comment]
@yurabakhtin For now, please implement it without a generic feature. For the generic approach I've added another issue.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/reportcontent/pull/62:

![report_admin](https://user-images.githubusercontent.com/6995524/227451408-5d2a1db3-676e-4705-bd85-874423a989e4.png)

![report_space](https://user-images.githubusercontent.com/6995524/227451405-d85dc3b1-dc31-4429-b7c2-799fc1e31ca0.png)
