### ISSUE TITLE
Space roles and access to reported content

### ISSUE THREAD

**Issue by Semir1212** [humhub/reportcontent#69]
HH 1.14.2
RC 1.0.2

Space Owner, Admin and Moderator should have access to reported content within a space and should receive a notification about it. It seems that Moderators are currently excluded.

**Comment by yurabakhtin** [comment]
@luke- @Semir1212 Done in PR https://github.com/humhub/reportcontent/pull/70.

Also I have detected the reporting is working only for Space and not for User containers, so I decided to hide this menu items on the User container:

![wrong_report_link](https://github.com/humhub/reportcontent/assets/6995524/953b4f07-cf33-4d97-816d-16aa92168be1)

**Comment by luke-** [comment]
@yurabakhtin Do I understand it correctly that no more profiles posts can be reported?

**Comment by yurabakhtin** [comment]
@luke- 

> Do I understand it correctly that no more profiles posts can be reported?

Yes, you understand this correctly. Or is it wrong and we should allow to report content and comment of the User container? If yes, then why don't we have the same manager for User as we have for Space?
I mean for Space we have this manager for the reported content:

![space_reported](https://github.com/humhub/reportcontent/assets/6995524/6938cafe-f340-4ee4-98bc-b72322939c08)

But we don't have such one for User. Maybe we should allow it and add new menu item in the Profile menu.
I think only the current User can manage the reports and probably system admins.
Also I think no reason to allow to report on Content record, it make sense to report only for Comment under user Content record. Do you agree?

Also on report we have the qustion: "For what reason do you want to report this content?" with options:

- Wrong Space
- Misleading
- Offensive
- Spam

I think the "Wrong Space" is not correct for User/Profile page, and it should be either renamed or removed when we will allow to report on User page.

**Comment by luke-** [comment]
Probably would be best if profile posts can be reported, but can only be edited/viewed by Global Admins. 
So there is no possibility for ContentContainer admins to see them separately.

If we could remove "Wrong Space" as a Reason that would be ideal. 

If you implement that, can you please implement tests for it here as well.

**Comment by yurabakhtin** [comment]
@luke- 

> Probably would be best if profile posts can be reported, but can only be edited/viewed by Global Admins. So there is no possibility for ContentContainer admins to see them separately.
> 
> If we could remove "Wrong Space" as a Reason that would be ideal.

Ok, I have this in commit https://github.com/humhub/reportcontent/pull/70/commits/db8cccda0e3256ce6f84b04dd52580656ffb6e9a.

> If you implement that, can you please implement tests for it here as well.

I will review later what tests can be added there, at this moment I just fixed broken tests after my new changes.

**Comment by yurabakhtin** [comment]
> > If you implement that, can you please implement tests for it here as well.
> 
> I will review later what tests can be added there, at this moment I just fixed broken tests after my new changes.

@luke- Commit https://github.com/humhub/reportcontent/pull/70/commits/04c9dcc979a44b26a1b2894c3104c2d04a3bd495.

The PR can be merged.
